### ISSUE TITLE
Folder needs to exist in order for the results to be written

### ISSUE THREAD

**Issue by alsmith151** [Chris1221/lanceotron#2]
Would it be possible to create the directory/ parent directories if they do not exist?

**Comment by Chris1221** [comment]
Good idea, I'm on it!

**Comment by Chris1221** [comment]
Should be fixed now @alsmith151, I added two tests to ensure that the functionality doesn't get dropped and put it up on pypi. Let me know if it works `pip install lanceotron==1.0.1`
